### ISSUE TITLE
"QT5" can only get installed on python3, while "opendr" can only get installed on python2

### ISSUE THREAD

**Issue by wswdx** [thmoa/smpl_viewer#2]
As mentioned in the title, I find it impossible to install both of the required package on python2 or python3? Could u give me some hints about? How did u make it? Thanks in advance~

**Comment by thmoa** [comment]
There are brew, conda and Ubuntu packages for pyqt5 and python2.

**Comment by vigorbird** [comment]
I also meet this problem, Thmoa, can you give orders of installation to pyqt5?
I use "conda install -c dsdale24 pyqt5 " to install pyqt5, but programme can not work.
